export { Home as Home} from '../pages/Home'
export { Lojas as Lojas } from '../pages/Lojas'
export { Perfil as Perfil } from '../pages/Perfil'
export { Contacte as Contacte } from '../pages/Contacte'
export { Cadastro_Empresa as CadastroE } from '../pages/Cadastro_Empresa'
export { Layout as Layout } from '../pages/Layout'
export { Cadastro_Usuario as CadastroU } from '../pages/Cadastro_Usuario'
export { Login as Login } from '../pages/Login'